### PR TITLE
Initial commit of the code base from .NET 6.0.

### PR DESCRIPTION
**Pull request by mockjv**

### CODE REVIEW

**Comment by mockjv** [comment]
Basic test of the examples is looking reasonable so going ahead and merging into master.

**Comment by mockjv** [comment]
@dregula I noticed your recent fork, so I figured I'd notify you that I took the liberty of updating the sources based on those found in .NET 6.0.1 if that's helpful for you.

**Comment by mockjv** [comment]
@dregula I noticed your recent fork, so I figured I'd notify you that I took the liberty of updating the sources based on those found in .NET 6.0.1 if that's helpful for you.

**Comment by dregula** [comment]
Thanks, Jason-
Having your smaller source was helpful to me in my analysis of an older SignalR system.
Turn’s out that the system I was trying to stress-test uses the older SignalR v1 negotiate protocol (GET instead of POST) and all the versions I tested of Crank failed to successfully negotaiate with this older server.
I am not a programmer, rather just a notch above the script-kiddie!
I tried to dig deep into the M$ source and override the negotiate code, but that proved beyond my meager abilities.
Keep up the good work!
-DR

**Pull request merged**
